services:
  postgres:
    image: postgres:17-alpine
    container_name: sd-generator-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - sd_generator_postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  sd_generator_postgres_data:
